info:
  app:
    name: mybatis-annotation
    version: vl.0.0
spring:
  profiles:
    active: dev
#  http:
#    encoding:
#    charset: UTF-8
#    enabled: true
#    force: true
  messages:
    encoding: UTF-8
  application:
    name: mybatis